### ISSUE TITLE
Freetype Attribute not found

### ISSUE THREAD

**Issue by vishaln15** [kkoomen/qbr#11]
AttributeError: module 'cv2.cv2' has no attribute 'freetype'

Completely new with CV. Found this a cool project to start with. I was unable to find a solution for the AttributeError. 
Thank you.

**Comment by kkoomen** [comment]
You're missing the `opencv-contrib-python` module. Run `pip install -r requirements.txt` to fix this.

**Comment by vishaln15** [comment]
I've tried installing it in multiple environments. I uninstalled and reinstalled with --no-cache-dir. I've installed it using the requirements.txt, still no good. On an unrelated note, I found pip3 installing the packages very slowly.

**Comment by kkoomen** [comment]
@vishaln15 You have to make sure that you _first_ install `opencv-python` and _then_ `opencv-contrib-python`. This order is important. You can try to uninstall both modules first and then install `opencv-python` and then `opencv-contrib-python`.

**Comment by shaoshenchen** [comment]
> @vishaln15 You have to make sure that you _first_ install `opencv-python` and _then_ `opencv-contrib-python`. This order is important. You can try to uninstall both modules first and then install `opencv-python` and then `opencv-contrib-python`.

no use on Win10
