### ISSUE TITLE
I don't have Gans365. I'm having issue to capture in a room with electric light

### ISSUE THREAD

**Issue by neuberfran** [kkoomen/qbr#8]
Hi,

This is my cube model:
![20210121_000843](https://user-images.githubusercontent.com/38701397/105275249-a0198a00-5b7d-11eb-8541-e3bbc620b278.jpg)

i need help adapting your project to my cube type

**Comment by kkoomen** [comment]
As I've mentioned in the README:

> One of the main things that killed me during developing this was color detection. It works for my room, but I bet it doesn't work for you, or you must have the same lighting and color scheme as I do.

You can play around with the settings [here](https://github.com/kkoomen/qbr/blob/master/src/colordetection.py#L17). I'm still hoping one day to have a better solution for this.

**Comment by neuberfran** [comment]
@kkoomen 

**Thanks for the time being for replying.
Yes, I read the README three times before trying.

Allow me to ask a few more questions (so that I can succeed in the project).

1) Could opencv2 solve this problem (of luminosity) more effectively?

2) Could tensorflow or tensorflow lite (I'm from the iot area) be more effective?

3) Currently, what technology could be more effective in this case? (using webcam, or recording the cube video and then rotating it manually, without a machine)?**

**Comment by neuberfran** [comment]
@kkoomen I would like you to keep me informed about this conversation that you will have with your friend

**Comment by neuberfran** [comment]
@kkoomen In this project here you are using opencv or opencv2. Do you think about migrating to opencv2?

**Comment by kkoomen** [comment]
The project is already using cv2.
